### ISSUE TITLE
Move docs research output here?

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/user-research#10]
@meiqimichelle would it be useful to move the output from the docs research into this repo? (i.e. the stuff linked from the bottom of the [distributed-kit readme](https://github.com/ipfs/user-research/tree/master/distributed-kit#related-links).) At the time, it didn’t seem like there was a good place to dump it and I didn’t want to add to the madness of so many repos.

If so, should it just be a sub-folder in `distributed-kit`?

**Comment by meiqimichelle** [comment]
@Mr0grog I'm on the fence. As long as documentation/research is accessible *from* this repo, I'm not terribly worried that it doesn't live here. However, I don't love that your really valuable work is buried at the bottom of the README.

As a a slight improvement, I was thinking of at least adding a usefully-named folder to this directory with a .md document in it with a very short summary of results and another link to your work.

What do you think? Would you prefer that the output live here?

**Comment by Mr0grog** [comment]
> I was thinking of at least adding a usefully-named folder to this directory with a .md document in it with a very short summary of results and another link to your work.

Great, I can do that. I also have to type up notes from interviewing Eric Tang (Livepeer). I’ll add them to the existing research results site and include any useful insights in the summary I post here.

> Would you prefer that the output live here?

I don’t have especially strong feelings on this. As long as it’s linked and pinned, it’s accessible (but we should probably update the link to point directly to the IPFS CID instead of the mutable DNSLink address it’s currently at). You can always move it here later (the full markdown source to build the gitbook site is also at the same address).

**Comment by meiqimichelle** [comment]
That sounds like a great plan -- thank you!

`update the link to point directly to the IPFS CID instead of the mutable DNSLink address it’s currently at` --> learn something new every day 😆
