### ISSUE TITLE
Synthesize existing pinning ux research

### ISSUE THREAD

**Issue by meiqimichelle** [ipfs/user-research#14]
What do we already know about the most common user journeys for configuring and interacting with pins in IPFS across various entrypoints?

This is related to #15 re documenting what those entrypoints actually are, to start with.

**Comment by meiqimichelle** [comment]
Pinning service API proposal by @lanzafame: https://github.com/ipfs/notes/issues/378

**Comment by meiqimichelle** [comment]
I've been putting links to existing documentation directly in the entry point list (then they're categorized and organized nicely). That list is here: https://gist.github.com/meiqimichelle/879a9b7ba89f441880dac656a43d2c61 .

**Comment by meiqimichelle** [comment]
`Outline the Various Applications of IPFS, with Use Cases and Dependencies` https://github.com/ipfs/ipfs/issues/230

**Comment by lanzafame** [comment]
Just want to clarify that the `Pinning Service API` is slightly different to the general pinning concept, in that the pinning service api is about how I tell someone else that I am paying to pin a file for me and that is all. Obviously, the Pinning Service API is affected if we change what `pinning` actually means 🙃

**Comment by meiqimichelle** [comment]
IPFS pinning 'current state / background' summarized here: https://gist.github.com/meiqimichelle/25d2221c08807841be7764b22f4a5bb5

**Comment by meiqimichelle** [comment]
Closing this issue for now because there's no active work on this right now. Plz re-open as needed.
