### ISSUE TITLE
README

### ISSUE THREAD

**Issue by daviddias** [ipfs/user-research#2]
@meiqimichelle can you expand on the README what are the goals of this repo, work already done and overall where people can find the User Research and how to interact with this repo? Thank you!

**Comment by meiqimichelle** [comment]
@diasdavid I haven't had a chance to initialize this repo yet. It is an empty placeholder. When I am back in the office next week, I hope to have time to really kick off organization here. (So, right now, there is nothing to interact with or see.)

**Comment by meiqimichelle** [comment]
@diasdavid take a peek -- see if the README works for now. If that works, plz close this issue. 

(Also, let me know if there's a standard README format I should follow. I looked at `js-ipfs` to start, tho not all of that seems relevant to this repo).

**Comment by daviddias** [comment]
It's a good start, I expect it to evolve to fit the needs as we start getting User Surveys and Roadmaps done. Thank you @meiqimichelle :)
