### ISSUE TITLE
Enable wiki on this repo

### ISSUE THREAD

**Issue by meiqimichelle** [ipfs/user-research#3]
I'm not sure who can do this. @diasdavid , @hsanjuan -- are you able to enable the wiki feature on this repo?

Thank you!

**Comment by daviddias** [comment]
Done. Do note that typically, the Wiki feature is never successful on Github projects, the versioning and PR reviews is not there. Every time we used it, people soon forgot about it. We always prefer to use markdown files instead.

**Comment by meiqimichelle** [comment]
@diasdavid thank you! I've used Wikis very successfully in the past for user research, roadmap, and data documentation on GitHub projects. It moves long-term information out of issues, which should be ephemeral, to a place they can live in a more book-like way. The main repo folder structure becomes just that -- a folder structure for ongoing work -- and the Wiki becomes the guidance (when the main repo README isn't enough). In any case, we'll see!
